export default {
  content: [
    "./index.html",
    "./AppRouter.js",
    "./home/**/*.{js,jsx}",
    "./components/**/*.jsx",
  ],
  ...{
    darkMode: "class",
    theme: {
      extend: {
        colors: {
          "on-tertiary-fixed": "#002022",
          "inverse-on-surface": "#2f3037",
          error: "#ffb4ab",
          "on-secondary-container": "#00311f",
          "on-primary": "#00354a",
          "on-surface-variant": "#bdc8d1",
          "surface-container-high": "#292a30",
          "surface-container-highest": "#34343b",
          background: "#121319",
          "on-error-container": "#ffdad6",
          "on-tertiary": "#00373a",
          "secondary-container": "#00a572",
          "primary-container": "#38bdf8",
          "on-secondary-fixed": "#002113",
          "on-tertiary-fixed-variant": "#004f53",
          "tertiary-container": "#00c4ce",
          "surface-variant": "#34343b",
          "on-background": "#e3e1ea",
          "on-error": "#690005",
          surface: "#121319",
          "inverse-primary": "#00668a",
          "on-tertiary-container": "#004c50",
          "surface-container-lowest": "#0d0e14",
          "tertiary-fixed-dim": "#00dce6",
          secondary: "#4edea3",
          "primary-fixed": "#c4e7ff",
          "error-container": "#93000a",
          "on-primary-container": "#004965",
          "secondary-fixed": "#6ffbbe",
          "inverse-surface": "#e3e1ea",
          outline: "#87929a",
          "surface-container-low": "#1a1b22",
          "tertiary-fixed": "#6ff6ff",
          "on-secondary": "#003824",
          "on-primary-fixed-variant": "#004c69",
          "on-surface": "#e3e1ea",
          "surface-dim": "#121319",
          "on-primary-fixed": "#001e2c",
          "surface-bright": "#383940",
          primary: "#8ed5ff",
          "primary-fixed-dim": "#7bd0ff",
          tertiary: "#00e2ed",
          "on-secondary-fixed-variant": "#005236",
          "surface-container": "#1e1f26",
          "surface-tint": "#7bd0ff",
          "secondary-fixed-dim": "#4edea3",
          "outline-variant": "#3e484f",
        },
        borderRadius: {
          DEFAULT: "0.125rem",
          lg: "0.25rem",
          xl: "0.5rem",
          full: "0.75rem",
        },
        spacing: {
          margin: "1rem",
          "space-lg": "1rem",
          "space-sm": "0.5rem",
          "space-xs": "0.25rem",
          "margin-desktop": "2rem",
          gutter: "1rem",
          "space-md": "0.75rem",
          "gutter-desktop": "1.5rem",
          "space-xl": "1.5rem",
        },
        fontFamily: {
          sans: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
          mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
          "headline-md": ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
          "body-lg": ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
          "label-md": [
            "JetBrains Mono",
            "ui-monospace",
            "SFMono-Regular",
            "Menlo",
            "monospace",
          ],
          "code-md": [
            "JetBrains Mono",
            "ui-monospace",
            "SFMono-Regular",
            "Menlo",
            "monospace",
          ],
          "code-lg": [
            "JetBrains Mono",
            "ui-monospace",
            "SFMono-Regular",
            "Menlo",
            "monospace",
          ],
          "headline-lg": ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
          "headline-xl": ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
          "label-sm": [
            "JetBrains Mono",
            "ui-monospace",
            "SFMono-Regular",
            "Menlo",
            "monospace",
          ],
          "headline-sm": ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
          "body-md": ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
          "headline-xl-mobile": ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
          "body-sm": ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
          "headline-lg-mobile": ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
        },
        fontSize: {
          "headline-md": [
            "22px",
            { lineHeight: "30px", letterSpacing: "-0.02em", fontWeight: "500" },
          ],
          "body-lg": [
            "16px",
            { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "400" },
          ],
          "label-md": [
            "12px",
            { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" },
          ],
          "code-md": [
            "12px",
            { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" },
          ],
          "code-lg": [
            "14px",
            { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "400" },
          ],
          "headline-lg": [
            "28px",
            {
              lineHeight: "36px",
              letterSpacing: "-0.025em",
              fontWeight: "600",
            },
          ],
          "headline-xl": [
            "40px",
            { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "600" },
          ],
          "label-sm": [
            "11px",
            { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" },
          ],
          "headline-sm": [
            "18px",
            {
              lineHeight: "26px",
              letterSpacing: "-0.015em",
              fontWeight: "600",
            },
          ],
          "body-md": [
            "14px",
            {
              lineHeight: "22px",
              letterSpacing: "-0.005em",
              fontWeight: "400",
            },
          ],
          "headline-xl-mobile": [
            "28px",
            { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" },
          ],
          "body-sm": [
            "13px",
            { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" },
          ],
          "headline-lg-mobile": [
            "24px",
            { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" },
          ],
        },
      },
    },
  },
};
